export const types = {
    CHANGE_MESSAGE: 'CHANGE_MESSAGE',
    OBTENIENDO_CLIMA: 'OBTENIENDO_CLIMA',
    ACTUALIZANDO_UBICACION: 'ACTUALIZANDO_UBICACION',
    ERROR_OBTENIENDO_CLIMA: 'ERROR_OBTENIENDO_CLIMA',
    OBTENIENDO_PAISES: 'OBTENIENDO_PAISES',
    PAISES_RECIBIDOS: 'PAISES_RECIBIDOS',
    ERROR_OBTENIENDO_PAISES: 'ERROR_OBTENIENDO_PAISES',
    LIMPIAR_PAISES: 'LIMPIAR_PAISES',
    PAIS_INGRESADO: 'PAIS_INGRESADO',
    PAIS_SELECCIONADO: 'PAIS_SELECCIONADO'
}

export const urls = {
    api: '/api/'
}